### ISSUE TITLE
Add a caret to search bar so users are aware of dropdown menu

### ISSUE THREAD

**Issue by dmcfaddengalway** [dirty-bits/uni-bites#18]
Consider adding a small caret to the right hand side of the sear bar on the index so users are aware of the drop down menu. Will also require positioning the drop down menu to appear on the right hand side of the search bar right before the search button

**Comment by dmcfaddengalway** [comment]
caret should appear inside search bar, and the search icon should reappear in the orange button

**Comment by jrohan1** [comment]
Caret added, drop down repositioned
